### ISSUE TITLE
Inconsistent behavior

### ISSUE THREAD

**Issue by drmbt** [mourendxu/TD-File-Collector#1]
Seems to only copy  one file of several, just made a session with a few jpgs and tiffs from the Samples folder. All files are listed and summed properly, but only the jellybeans tif gets copied. Also seeing some bugs on line 60 with the dst_dir. Maybe a problem in the 2020 build?

**Comment by mourendxu** [comment]
Could you update the repo and try again? It seems like one of the files had an extension that my code didn't recognize.

Thank you for filing the bug!

**Comment by mourendxu** [comment]
I take that this has been fixed. I am closing this issue.
